"""Built-in device personas - internally-consistent identity seeds.

Each persona wires a coherent set of navigator + screen + ClientHints values
so the fingerprint does not contradict itself (a major detection vector).
"""

PERSONAS = {
    "win-chrome": {
        "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
        "(KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36",
        "platform": "Win32",
        "platform_version": "15.0.0",
        "architecture": "x86",
        "bitness": "64",
        "sec_ch_ua_mobile": "?0",
        "sec_ch_ua_platform": '"Windows"',
        "sec_ch_ua": '"Not/A)Brand";v="8", "Chromium";v="126", "Google Chrome";v="126"',
        "ua_full_version_list": '"Not/A)Brand";v="8.0.0.0", "Chromium";v="126.0.6478.114", '
        '"Google Chrome";v="126.0.6478.114"',
        "hardware_concurrency": 8,
        "device_memory": 8,
        "screen_width": 1920,
        "screen_height": 1080,
        "color_depth": 24,
        "device_pixel_ratio": 1.0,
        "timezone": "America/New_York",
        "locale": "en-US",
        "languages": ["en-US", "en"],
        "webgl_vendor": "Google Inc. (NVIDIA)",
        "webgl_renderer": "ANGLE (NVIDIA, NVIDIA GeForce GTX 1660 Direct3D11 vs_5_0 ps_5_0, D3D11)",
        "fonts": ["Arial", "Calibri", "Cambria", "Comic Sans MS", "Consolas",
                  "Courier New", "Georgia", "Segoe UI", "Tahoma",
                  "Times New Roman", "Trebuchet MS", "Verdana"],
    },
    "mac-safari": {
        "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 "
        "(KHTML, like Gecko) Version/17.4 Safari/605.1.15",
        "platform": "MacIntel",
        "platform_version": "14.4.0",
        "architecture": "arm",
        "bitness": "64",
        "sec_ch_ua_mobile": "?0",
        "sec_ch_ua_platform": '"macOS"',
        "sec_ch_ua": None,
        "ua_full_version_list": None,
        "hardware_concurrency": 10,
        "device_memory": 8,
        "screen_width": 2560,
        "screen_height": 1440,
        "color_depth": 30,
        "device_pixel_ratio": 2.0,
        "timezone": "America/Los_Angeles",
        "locale": "en-US",
        "languages": ["en-US", "en"],
        "webgl_vendor": "Apple Inc.",
        "webgl_renderer": "Apple M1 Pro",
        "fonts": ["Arial", "Avenir", "Courier", "Geneva", "Helvetica",
                  "Helvetica Neue", "Lucida Grande", "Monaco", "Optima",
                  "Palatino", "Times", "Verdana"],
    },
    "linux-ff": {
        "user_agent": "Mozilla/5.0 (X11; Linux x86_64; rv:127.0) Gecko/20100101 Firefox/127.0",
        "platform": "Linux x86_64",
        "platform_version": "6.6.0",
        "architecture": "x86",
        "bitness": "64",
        "sec_ch_ua_mobile": "?0",
        "sec_ch_ua_platform": '"Linux"',
        "sec_ch_ua": None,
        "ua_full_version_list": None,
        "hardware_concurrency": 12,
        "device_memory": 16,
        "screen_width": 2560,
        "screen_height": 1440,
        "color_depth": 24,
        "device_pixel_ratio": 1.0,
        "timezone": "Europe/Berlin",
        "locale": "de-DE",
        "languages": ["de-DE", "de", "en-US", "en"],
        "webgl_vendor": "Mesa",
        "webgl_renderer": "Mesa Intel(R) Iris(R) Xe Graphics (TGL GT2)",
        "fonts": ["DejaVu Sans", "DejaVu Serif", "DejaVu Sans Mono",
                  "Liberation Sans", "Liberation Serif", "Liberation Mono",
                  "Cantarell", "Ubuntu", "Noto Sans"],
    },
    "android-mobile": {
        "user_agent": "Mozilla/5.0 (Linux; Android 14; Pixel 8) AppleWebKit/537.36 "
        "(KHTML, like Gecko) Chrome/126.0.0.0 Mobile Safari/537.36",
        "platform": "Linux armv8l",
        "platform_version": "14.0.0",
        "architecture": "",
        "bitness": "64",
        "sec_ch_ua_mobile": "?1",
        "sec_ch_ua_platform": '"Android"',
        "sec_ch_ua": '"Not/A)Brand";v="8", "Chromium";v="126", "Google Chrome";v="126"',
        "ua_full_version_list": '"Not/A)Brand";v="8.0.0.0", "Chromium";v="126.0.6478.114", '
        '"Google Chrome";v="126.0.6478.114"',
        "hardware_concurrency": 8,
        "device_memory": 8,
        "screen_width": 412,
        "screen_height": 915,
        "color_depth": 24,
        "device_pixel_ratio": 2.625,
        "timezone": "Asia/Tokyo",
        "locale": "ja-JP",
        "languages": ["ja-JP", "en-US", "en"],
        "webgl_vendor": "Google Inc. (ARM)",
        "webgl_renderer": "ANGLE (ARM, Mali-G715, OpenGL ES 3.2)",
        "fonts": ["Roboto", "Noto Sans JP", "Noto Sans CJK JP", "Droid Sans"],
    },
}

