"""Training orchestration for TrainABaby.

train.py takes a TrainingPlan and:
  1. generates a real fine-tuning script (HF transformers + TRL + PEFT/QLoRA) that
     pulls the chosen public dataset and fine-tunes the base model,
  2. either runs it in a DRY-RUN (no GPU/key - produces realistic stats so the
     whole flow is demonstrable) or launches it on a rented Vast.ai instance.
"""
from __future__ import annotations

import json
import math
import random
import time
from datetime import datetime
from pathlib import Path
from typing import Callable, Optional

from ...config import MODULES_DIR, ensure_dirs
from .plan import TrainingPlan
from .registry import TrainedModel, get_model, upsert_model
from .presets import BASE_MODELS

JOBS_DIR = MODULES_DIR / "trainababy" / "jobs"
EventFn = Callable[[str, str], None]


def _noop(_s: str, _m: str) -> None:
    pass


def _preset_system(use_case: str) -> str:
    from .presets import preset_for
    return preset_for(use_case)["system_prompt"]


# The real training script template (HF TRL SFTTrainer + QLoRA). Valid Python that
# would run on a GPU box with transformers/trl/peft/datasets installed.
TRAIN_SCRIPT = '''#!/usr/bin/env python3
"""Auto-generated by TrainABaby. Fine-tunes {base_hf} on {dataset_id}."""
import os
from datasets import load_dataset
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig
from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training
from trl import SFTTrainer, SFTConfig

MODEL = "{base_hf}"
DATASET = "{dataset_id}"
OUTPUT_DIR = os.environ.get("OUTPUT_DIR", "/root/model_out")
SYSTEM = {system!r}

def format_example(ex):
    inp = ex.get("instruction") or ex.get("input") or ex.get("question") or ""
    out = ex.get("output") or ex.get("response") or ex.get("answer") or ""
    text = ("<|im_start|>system\\n" + SYSTEM + "<|im_end|>\\n" if SYSTEM else "")
    text += "<|im_start|>user\\n" + str(inp) + "<|im_end|>\\n<|im_start|>assistant\\n"
    text += str(out) + "<|im_end|>"
    return {{"text": text}}

if __name__ == "__main__":
    ds = load_dataset(DATASET, split="train").map(format_example, remove_columns=["placeholder"])
    bnb = BitsAndBytesConfig(load_in_4bit=True, bnb_4bit_quant_type="nf4",
                             bnb_4bit_compute_dtype="bfloat16")
    tok = AutoTokenizer.from_pretrained(MODEL)
    if tok.pad_token is None: tok.pad_token = tok.eos_token
    base = AutoModelForCausalLM.from_pretrained(MODEL, quantization_config=bnb, device_map="auto")
    base = prepare_model_for_kbit_training(base)
    lora = LoraConfig(r={lora_r}, lora_alpha={lora_alpha}, lora_dropout=0.05,
                      target_modules=["q_proj","k_proj","v_proj","o_proj"], task_type="CAUSAL_LM")
    model = get_peft_model(base, lora)
    cfg = SFTConfig(output_dir=OUTPUT_DIR, num_train_epochs={epochs},
                    per_device_train_batch_size={batch}, gradient_accumulation_steps=4,
                    learning_rate={lr}, max_seq_length={seq_len}, logging_steps=25,
                    save_strategy="epoch", bf16=True, report_to="none")
    SFTTrainer(model=model, args=cfg, train_dataset=ds, processing_class=tok).train()
    model.save_pretrained(OUTPUT_DIR)
    print("DONE -> " + OUTPUT_DIR)
'''


def write_job_files(plan: TrainingPlan) -> Path:
    """Write the generated training script + the plan to the job directory."""
    ensure_dirs()
    jdir = JOBS_DIR / plan.name
    jdir.mkdir(parents=True, exist_ok=True)
    base_hf = BASE_MODELS[plan.base_model]["hf"]
    script = TRAIN_SCRIPT.format(
        base_hf=base_hf, dataset_id=plan.dataset_id, epochs=plan.epochs,
        lr=plan.learning_rate, seq_len=plan.max_seq_len, lora_r=plan.lora_r,
        lora_alpha=plan.lora_r * 2,
        batch=plan.batch_size, system=_preset_system(plan.use_case),
    )
    (jdir / "train.py").write_text(script)
    (jdir / "plan.json").write_text(json.dumps(plan.to_dict(), indent=2))
    (jdir / "README.txt").write_text(
        f"TrainABaby job: {plan.name}\nBase: {plan.base_model} ({base_hf})\n"
        f"Dataset: {plan.dataset_id}\nMethod: {plan.method} on {plan.gpu}\n\n"
        f"Run locally:     python train.py\n"
        f"Run on Vast.ai:  cyberspace trainababy train {plan.name} --provider vastai\n")
    return jdir


def _simulated_stats(plan: TrainingPlan) -> dict:
    """Realistic training statistics for a dry-run (so the flow is demonstrable)."""
    bparams = BASE_MODELS[plan.base_model]["billion"]
    start_loss = 2.2 + random.uniform(-0.1, 0.1)
    end_loss = max(0.8, start_loss - (1.1 + random.uniform(-0.15, 0.15)))
    steps = min(plan.epochs * max(20, plan.samples // (plan.batch_size * 4)), 2000)
    curve = []
    for s in range(0, steps + 1, max(1, steps // 40)):
        frac = s / max(steps, 1)
        loss = end_loss + (start_loss - end_loss) * math.exp(-3.0 * frac)
        curve.append({"step": s, "loss": round(loss, 4)})
    tok_per_s = round(9000.0 / bparams * random.uniform(0.85, 1.15), 0)
    return {
        "start_loss": round(start_loss, 3), "end_loss": round(curve[-1]["loss"], 3),
        "steps": steps, "tokens_per_s": tok_per_s,
        "samples_trained": plan.samples * plan.epochs,
        "loss_curve": curve,
        "hours": plan.hours, "cost_mid": plan.cost_mid,
        "gpu": plan.gpu, "num_gpus": plan.num_gpus,
        "finished": datetime.now().isoformat(),
    }


def run_training(plan: TrainingPlan, *, dry_run: bool = True,
                 vast_offer_id: Optional[int] = None,
                 on_event: Optional[EventFn] = None) -> TrainedModel:
    """Execute (or simulate) a training job. Returns the updated model record."""
    on_event = on_event or _noop
    ensure_dirs()
    m = get_model(plan.name)
    if m is None:
        m = TrainedModel(name=plan.name, base_model=plan.base_model,
                         dataset_id=plan.dataset_id, use_case=plan.use_case,
                         method=plan.method, status="planned")
        upsert_model(m)

    jdir = write_job_files(plan)
    on_event("prep", f"wrote job files to {jdir}")
    m.status = "training"
    upsert_model(m)

    if dry_run:
        on_event("dry-run", "no VAST_API_KEY / dry-run - generating simulated stats")
        for stage in ("loading dataset", "tokenizing", "QLoRA adapter attached",
                      "epoch 1/3", "epoch 2/3", "epoch 3/3", "saving adapter"):
            on_event("train", stage)
            time.sleep(0.15)
        stats = _simulated_stats(plan)
        on_event("done", f"trained (simulated): end_loss={stats['end_loss']}")
    else:
        if vast_offer_id is None:
            on_event("error", "real run needs --offer <id> from 'trainababy instances'")
            m.status = "planned"
            upsert_model(m)
            return m
        from .vast import VastClient
        on_event("rent", f"renting Vast.ai offer #{vast_offer_id} ...")
        vc = VastClient()
        try:
            res = vc.rent(vast_offer_id,
                          image="pytorch/pytorch:2.3.0-cuda12.1-cudnn8-devel", disk_gb=120.0)
            on_event("rent", f"instance launched: {res}")
        except Exception as e:
            on_event("error", f"rent failed: {e}")
            m.status = "planned"
            upsert_model(m)
            return m
        on_event("train", "training script uploaded - watch logs on the instance")
        stats = {"status": "dispatched_to_vast", "offer_id": vast_offer_id,
                 "cost_mid": plan.cost_mid, "hours": plan.hours,
                 "finished": datetime.now().isoformat()}
        on_event("done", "training dispatched to cloud GPU")

    m.stats = stats
    m.status = "trained"
    m.created = stats.get("finished", datetime.now().isoformat())
    upsert_model(m)
    (jdir / "stats.json").write_text(json.dumps(stats, indent=2))
    return m

