"""Model serving for RoboDaddy.

The implemented path writes a local Ollama Modelfile and issues an API key for
cyberspace's custom-provider configuration. Cloud serving targets are not
provisioned here; training jobs only dispatch to Vast.ai and record progress.
"""
from __future__ import annotations

import textwrap
from datetime import datetime
from pathlib import Path
from typing import Callable, Optional

from ...config import MODULES_DIR, ensure_dirs
from .registry import TrainedModel, get_model, issue_key, upsert_model

SERVE_DIR = MODULES_DIR / "robodaddy" / "serve"
EventFn = Callable[[str, str], None]


def _noop(_s: str, _m: str) -> None:
    pass


def _ollama_modelfile(model: TrainedModel) -> str:
    return textwrap.dedent(f"""\
        # Auto-generated by RoboDaddy
        FROM {model.base_model}
        PARAMETER temperature 0.2
        SYSTEM \"\"\"{model.use_case} specialist trained by RoboDaddy.\"\"\"
        # adapter weights would be merged here for a real fine-tune
        """)


def serve(model_name: str, *, target: str = "ollama", port: int = 11435,
          on_event: Optional[EventFn] = None) -> tuple[TrainedModel, str]:
    """Deploy a trained model. Returns (model, api_key).

    target: 'ollama' (local, free).
    Issues an OpenAI-compatible API key and marks the model served.
    """
    on_event = on_event or _noop
    ensure_dirs()
    m = get_model(model_name)
    if m is None:
        raise ValueError(f"no trained model named '{model_name}'. Run train first.")
    if m.status not in ("trained", "served"):
        raise ValueError(f"model '{model_name}' status is '{m.status}', not 'trained'.")

    SERVE_DIR.mkdir(parents=True, exist_ok=True)
    sdir = SERVE_DIR / model_name
    sdir.mkdir(parents=True, exist_ok=True)

    if target == "ollama":
        on_event("serve", f"local Ollama @ localhost:{port}")
        (sdir / "Modelfile").write_text(_ollama_modelfile(m))
        endpoint = f"http://localhost:{port}/v1"
        note = "local ollama (OpenAI-compatible). Run: ollama serve (or via the key)."
        on_event("serve", f"wrote Modelfile -> {sdir/'Modelfile'}")
        on_event("serve", f"to load: ollama create {model_name} -f {sdir/'Modelfile'}")
    elif target == "vastai":
        raise ValueError("Vast.ai serving is not implemented; use --target ollama or register an external endpoint manually.")
    elif target == "groq_lpu":
        raise ValueError("Groq upload/serving is not implemented; use --target ollama or register an external endpoint manually.")
    else:
        raise ValueError(f"unknown serve target '{target}'")

    key = issue_key(model_name, endpoint, note=note)
    on_event("key", f"issued API key: {key.key[:16]}... (full key in `robodaddy keys`)")
    on_event("done", f"endpoint: {endpoint}")
    # Reload the model so it reflects the updated endpoint/status.
    m = get_model(model_name) or m
    return m, key.key


def use_as_cyberbot(model_name: str) -> tuple[str, str]:
    """Configure cyberbot to use a served model as its LLM (custom provider).

    Returns (endpoint, api_key) and writes them to ~/.cyberspace/agent.json.
    """
    m = get_model(model_name)
    if m is None or m.status != "served" or not m.endpoint:
        raise ValueError(f"model '{model_name}' is not served yet. Run: cyberspace robodaddy serve {model_name}")
    from ...agent.config import is_configured, load_config, save_config
    from ...agent.llm import LLMConfig
    cfg = load_config() if is_configured() else LLMConfig()
    cfg.provider = "custom"
    cfg.base_url = m.endpoint
    # Fetch the key for this model.
    from .registry import list_keys
    keys = [k for k in list_keys() if k.model_name == model_name]
    if keys:
        cfg.api_key = keys[0].key
    cfg.model = model_name
    save_config(cfg)
    return m.endpoint, cfg.api_key
